version: "2"

services:
    
    nodeserver:
        container_name: ngarric_node
        image: "node:alpine"
        user: "node"
        working_dir: /home/node/
        volumes:
            - ./node:/home/node/
        ports:
            - "10041:3000"
        command: "npm start"
        
    mongodb:
        container_name: ngarric_mongodb2
        image: "mongo:7.0"

        volumes:
            - ./mongo:/data/db


